name: helmet_license
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6

  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.1
  geolocator: ^13.0.1
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  geocoding: ^3.0.0
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2

  lottie: ^3.1.2
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1
  flutter_stripe: ^11.0.0
  flutter_dotenv: ^5.1.0
  razorpay_flutter: ^1.3.7
  loading_animation_widget: ^1.2.1
  tflite_flutter: ^0.11.0
  tflite_flutter_helper_plus: ^0.0.2
  image: ^3.3.0
  camera: ^0.10.6
  path_provider: ^2.1.5
  firebase_ml_model_downloader: ^0.3.1+5
  google_mlkit_text_recognition: ^0.14.0
  google_ml_kit: ^0.19.0
  http: ^1.0.0
  video_player: ^2.9.2
  flutter_vision: ^1.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/background.jpeg
    - assets/background1.jpeg
    - assets/google-symbol.png
    - assets/Animation - 1727795283043.json
    - assets/best_float32.tflite
    - assets/labels.txt
    - assets/lp.jpg
    - assets/hel.jpg


  